### ISSUE TITLE
Test script em perl nao funciona corretamente no Arch linux

### ISSUE THREAD

**Issue by leohahn** [schnorr/comp#1]
Os comandos de teste funcionam normalmente no ubuntu, porém no arch linux eles falham.
Eu rodei os testes com `ctest -R e1 --verbose` e eu recebi um erro:

```
1: Test command: /usr/bin/perl "-I" "./tests/scripts" "./tests/scripts/tesh" "/home/lhahn/dev/c/pc/tests/e1/avaliacao_00.tesh"
1: Test timeout computed to be: 9.99988e+06
1: Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE (\w+)(?::[=-][^}]*)?}/ at ./tests/scripts/tesh line 345.
 1/32 Test  #1: e1_avaliacao_00 ..................***Failed    0.06 sec
test 2
      Start  2: e1_avaliacao_01
```

Acontece que a minha versao de perl está reclamando de uma chave sem escape na linha 345 do script. Quando eu coloco o escape na chave o problema é resolvido.

Requisitos para reproduzir:
- perl 5 version 26.
- arch linux
- cmake 3.9.1

Porém acho que o problema é uma incompatibilidade de versoes de perl talvez.

**Comment by schnorr** [comment]
Ele foi atualizado no repositório de referência. Poderias verificar que agora ele funciona no ARCH LINUX?

**Comment by leohahn** [comment]
Ops, acabei criando o issue no repositório errado.
Está funcionando agora, obrigado.
