### ISSUE TITLE
PDFs do conteúdo

### ISSUE THREAD

**Issue by rafaelcalcada** [schnorr/comp#11]
Olá professor,

No meu trabalho não tenho o Linux instalado e também não posso instalar nenhum programa nas máquinas. Isso impede que no meu tempo livre aqui no trabalho eu produza os PDFs com o conteúdo pra estudar.

Disponibilizar os PDFs aqui no Github seria uma boa :)

**Comment by schnorr** [comment]
Disponibilizar arquivos binários (com PDFs) em GIT não é uma boa prática. Como alternativa, baixe-os aqui: www.inf.ufrgs.br/~schnorr/comp.tar.gz
