### ISSUE TITLE
Novos tipos

### ISSUE THREAD

**Issue by GuilhermeChaves** [schnorr/comp#12]
Não consegui entender claramente como funciona a declaração de novostipos da etapa 2.
Poderia fornecer um exemplo?

**Comment by schnorr** [comment]
Segue:

```
class meu_novo_tipo [
  protected int meu_inteiro;
  public float meu_float;
  private string zero
];
```

O último campo não se termina por `;` pois este, na listagem de campos, apenas os separa.

**Comment by GuilhermeChaves** [comment]
OK, porém na especificação está dizendo que os campos são separados por ':' . Ou mudou para ; agora ?

**Comment by schnorr** [comment]
Obrigado @GuilhermeChaves pela correção; já atualizei minha resposta acima.
