### ISSUE TITLE
Soma de literais

### ISSUE THREAD

**Issue by lbassis** [schnorr/comp#14]
Como literais numéricos podem começar com + (ou -), ao escrever uma expressão do tipo 5+2, o analisador léxico entende como se fossem dois literais, causando um erro sintático mais tarde. No entanto, as expressões 5+ 2 e 5++2 estão corretas sintaticamente. É preciso alterar o analisador léxico de alguma maneira para permitir expressões do tipo 5+2 ou podemos considerar esse caso fora da sintaxe da linguagem?

**Comment by schnorr** [comment]
É preciso alterar o analisador léxico para que literais inteiros (ou de ponto flutuante) não possam mais ser precedidos de - ou +.
