### ISSUE TITLE
na atribuicao com "identificador.campo = expressão", o campo é um tipo primitivo?

### ISSUE THREAD

**Issue by celuddo** [schnorr/comp#19]
por ex: nome.string = "marcelo"; ?

**Comment by schnorr** [comment]
Não. O campo é o nome do campo que foi informado na declaração de novo tipo.

Se o tipo novo foi declarado assim:
`class MEUTIPO [ string nome : int idade ];`
a atribuição para o campo nome aconteceria assim:
```
  MEUTIPO umavariavel;
  umavariavel.nome = "Dumbledore";
  umavariavel.idade = 10000;
```
