### ISSUE TITLE
Dúvida sobre "Enriquecimento da tabela de símbolos"

### ISSUE THREAD

**Issue by FranciscoKnebel** [schnorr/comp#20]
Implementação E2.
> O conteúdo de cada entrada na tabela de símbolos deve ter pelo menos três campos: número da linha da última ocorrência do lexema, o tipo do token da última ocorrência, e o valor do token convertido para o tipo apropriado (inteiro int, ponto-flutuante float, caractere char, `booleano bool `ou cadeia de caracteres char*). O segundo campo, representado pelo tipo do token deve ser o mesmo utilizado na chave da entrada.

Segundo a definição da E1, os literais booleanos não são inseridos na tabela de símbolos, apenas inteiro, ponto flutuante, char, string e identificadores. Desconsiderar esse valor booleano então?

PS: é o que foi feito.

**Comment by schnorr** [comment]
Em um cenário ideal, seria melhor seguir a definição da E2, ou seja, adicionar o booleano na tabela de símbolos.
