### ISSUE TITLE
Precedência dos operadores aritméticos

### ISSUE THREAD

**Issue by rafaelcalcada** [schnorr/comp#21]
Os operadores aritméticos (+ - * / %) tem alguma ordem de precedência? Devemos seguir a precedência matemática (multiplicação e divisão precede soma e subtração)? 

Segundo a especificação, a única precedência que deve ser obedecida é a dos parênteses.

**Comment by schnorr** [comment]
Vocês devem seguir a precedência matemática de operadores.
