### ISSUE TITLE
Constantes globais

### ISSUE THREAD

**Issue by rafaelcalcada** [schnorr/comp#22]
Professor, por que as variáveis locais podem ser precedidas de const e as globais não? Constantes geralmente são globais e não locais. Essa definição da gramática leva a um conflito de shift/reduce difícil de solucionar. Até agora não encontramos solução.

**Comment by DenysonJ** [comment]
Na verdade o contexto em que ambas declarações aparecem são totalmente diferentes. Como as variáveis locais só podem ser declaradas dentro dos blocos nas funções, o estados em que as mesmas manifestam-se dentro do algoritmo do parser são distintas. Olhando o parser.output tu consegues constatar isso.
