### ISSUE TITLE
Lista de comandos do laço "for"

### ISSUE THREAD

**Issue by rafaelcalcada** [schnorr/comp#23]
Segundo a especificação, a lista do "for" é uma lista de comandos. Porém o único comando que faz sentido dentro de um laço "for" é o de atribuição. Se permitirmos que qualquer comando faça parte da lista, vamos ter a situação aberrante em que seria possível colocar comandos de input/output ou até mesmo outros laços dentro da lista de comandos do "for".

Por essa razão achamos por bem que a lista do for de nosso trabalho admite apenas comandos de atribuição. Estamos certos?

**Comment by DenysonJ** [comment]
Os comandos input e output ja estão listados como "proíbidos" na especificação, assim como o comando case. Entretando os outros não, parece que pode ter outros comandos de controle de fluxo nessa lista. Mas também achei estranho isso.

Além do comando de atribuição, o comando de declaração também faz sentido.
