### ISSUE TITLE
Expressões de caracteres

### ISSUE THREAD

**Issue by rafaelcalcada** [schnorr/comp#24]
Olá professor,

A especificação apenas menciona que uma expressão pode ser do tipo "expressão de caracteres". Porém não define o que deve ser entendido por "expressão de caracteres":
- pode ser um literal string ou char, apenas;
- pode ser um literal string, admitindo concatenações com "+", ou um literal char;
- pode ser qualquer operação tendo literais string e char como operandos à esquerda ou direita; etc.

Implementamos o mais fácil: uma expressão de caracteres pode ser um literal string ou char, apenas. Estamos certos?

**Comment by schnorr** [comment]
Isso fica de fato em aberto na especficação, mas acho que a abordagem por vocês adotada está bem. Nota que sendo uma expressão um literal string e char, as operações sobre esses elementos só serão definidas mais tarde, quando poderemos de fato sobrecarregar o operador +, por exemplo.
