### ISSUE TITLE
Adiamento avaliação etapa 3

### ISSUE THREAD

**Issue by renghp** [schnorr/comp#26]
Eu e uns colegas percebemos que haverá muitas datas de trabalhos e provas coincidindo com a entrega da etapa 3 do trabalho. Visto que houve a possibilidade de adiar a etapa 2, e isso acabou não ocorrendo, gostaríamos de saber se há a possibilidade de adiar a entrega da etapa 3 em uma semana, a fim de podermos nos dedicar melhor à implementação do trabalho.

**Comment by schnorr** [comment]
Adiamos de 2 dias.
