### ISSUE TITLE
Problema com vetores no foreach

### ISSUE THREAD

**Issue by DenysonJ** [schnorr/comp#27]
Gostaríamos de saber se a linguagem aceita algo como:
`foreach(x:vetor){}`

Sendo vetor, por exemplo, declarado de forma global assim:
`int vetor[10];`

**Comment by schnorr** [comment]
Da especificação da E2, temos `foreach (identificador: lista) bloco`, logo em seguida temos `A lista do foreach é uma lista de expressões separadas por vírgula.` (confirme na E2 a sintaxe desta lista). Ou seja, isso signifca que a lista não pode ser um vetor, mas a lista pode ser composta, explicitamente, de posições de um vetor.
