### ISSUE TITLE
Escopos e declaração de variáveis

### ISSUE THREAD

**Issue by DenysonJ** [schnorr/comp#28]
Há uma ambiguidade na especificação da etapa 4, nessa frase:

> Variáveis com o mesmo nome podem existir em escopos diferentes.

Isso permite redeclarar uma variável global em um escopo local? Ou somente redeclarar variáveis em escopos locais diferentes?

**Comment by schnorr** [comment]
Olá @DenysonJ, duas variáveis com meu nome podem existir ao mesmo tempo em escopos diferentes. Como nossa linguagem tem apenas dois escopos possíveis (local às funções, e global), é possível termos uma variável global e uma variável local à uma função com o mesmo nome. Nesse caso, correto, a variável local "esconde" a variável global devido ao uso do mesmo nome.
