### ISSUE TITLE
Criação de Código: foreach

### ISSUE THREAD

**Issue by Fillps** [schnorr/comp#29]
Ao iniciar a criação de código do foreach não entendi como a lógica dele funciona.
Na E2 temos:
> foreach (identificador: lista) bloco
>A lista do foreach é uma lista de expressões separadas por vírgula.

O que acontece em cada iteração com o identificador e a lista de expressões?

**Comment by schnorr** [comment]
O identificador assume um valor da lista de expressões, assumindo que este valor estará em um variável temporária após a avaliação (execução do código) da expressão. O identificador assumirá, a cada iteração, um valor da lista, na ordem que aparece no código.
