### ISSUE TITLE
Literal 'char' vazio

### ISSUE THREAD

**Issue by AvatarHurden** [schnorr/comp#30]
Na definição da Etapa 1 do trabalho (Análise Léxica), é dito que um `char` é "um **único** caractere entre aspas simples". 

Nos exemplos, porém, existe um literal `char` vazio (`''`), sem nenhum caractere entre as aspas.

Devemos fazer a implementação conforme a definição escrita ou de forma a aceitar todos os exemplos dados?

**Comment by schnorr** [comment]
Olá @AvatarHurden, obrigado por perceber isso. Acabo de fazer um push substituindo o `''` por `' '`, ou seja, com um espaço em branco. Eu diria até que o caso  `''` (sem nada no meio) pode ser visto como um erro léxico.
