### ISSUE TITLE
Dúvida sobre notação científica

### ISSUE THREAD

**Issue by schnorr** [schnorr/comp#31]
Dúvida de um aluno:

"A notação científica é possível para números ponto flutuantes utilizando um E ou e seguindo de um número positivo ou negativo inteiro."

Isso significa, tem que ser capturado inicialmente um float na forma correta de notação cientifica (https://pt.wikipedia.org/wiki/Nota%C3%A7%C3%A3o_cient%C3%ADfica) entre 1 e 10 e ai entao seguido do e ou E ? E depois de encontrado ele é "eguindo de um número positivo ou negativo inteiro", isso quer dizer, por exemplo 3.2e+10 e 3.2e-10 seriam validos, mas caso nao se tenha sinal (aka 3.2e10) isso também seria valido ?

**Comment by schnorr** [comment]
Essa questão é parecida com a #8. Mas respondendo novamente: as entradas `3.2e+23` e `3.2e-23` são válidas, assim como `3.2e23`, pois neste último caso trata-se de um número inteiro positivo após o `e`.

**Comment by AvatarHurden** [comment]
@schnorr, números ponto flutuante precisam seguir à risca a notação científica para serem válidos (com a mantissa entre 1 e 10)?

O seguinte float seria inválido?
`12.3e10`

**Comment by schnorr** [comment]
Olá @AvatarHurden , a notação científica de fato só pode ter mantissa entre 1 e 10. No entanto, na maioria das linguagens de programação se assume que o valor é 10 e apresenta após o símbolo `e` ou `E` apenas o expoente (ou seja, a ordem de grandeza). É este último caso que espero ver no trabalho, pois se aproxima mais com LPs.

**Comment by schnorr** [comment]
Alguns chamam de Notação E, [veja mais detalhes](https://pt.wikipedia.org/wiki/Nota%C3%A7%C3%A3o_cient%C3%ADfica#Nota%C3%A7%C3%A3o_E).

**Comment by schnorr** [comment]
Sim.
