### ISSUE TITLE
Especificação de String literal

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#32]
Não há especificação para String literal na primeira etapa do projeto.

Quais casos específicos devem ser considerados?
1. Aspas escapada
```C
"\""
```
2. String vazia
```C
""
```
3. String multilinha usando barra invertida
```C
"linha 1\
linha2"
```
4. String multilinha usando duas Strings?
```C
"linha1"
"linha2"
```
5. Coisas que são possíveis em C mas não deveriam
```C
"\"""""linha1\
linha2"
"linha3"
```
6. Caso inválido
```C
"linha1
linha2"
```

Em C, os 5 primeiros casos são válidos. E quando usados numa atribuição, resultam numa única string.
```C
char *a = "\"""""linha1\
linha2"
"linha3"; // Válido
```

Exemplo:

```C
#include <stdio.h>

int main()
{
    printf("\""); // 1

    printf("\n");

    printf(""); // 2

    printf("\n");

    printf("linha1\
    linha2"); // 3

    printf("\n");

    printf("linha1"
    "linha2"); // 4

    printf("\n");

    printf("\"""""linha1\
    linha2"
    "linha3"); // 5

    return 0;
}
```

**Comment by schnorr** [comment]
Obrigado @lanahra pelo relato do tratamento de strings da linguagem C. No caso do nosso projeto de compilador, vamos simplificar e tratar strings como sendo algo `"assim"` simplesmente, com a opção de ter strings `""` vazias. Ou seja, não há a necessidade de tratar aspas duplas escapadas, nem strings multilinha com escape, nem strings multilinha. No entanto, caso houver interesse de implementá-las, sinta-se à vontade. Perceba que a string multilinha pode ser tratada através de uma abordagem sintática.
