### ISSUE TITLE
Como tratar um erro léxico em no token de caractere simples

### ISSUE THREAD

**Issue by schnorr** [schnorr/comp#33]
Quando há uma tentativa de fazer um char com mais de um caractere: `'cc'`, o analisador deve retornar tudo como um erro ou deve separar como `TOKEN_ERRO['] TK_IDENTIFICADOR[cc] TOKEN_ERRO[']`?

**Comment by schnorr** [comment]
Eu prefiro responder dizendo que deve retornar tudo como um **único erro**. Dito isso, a especificação não deixa claro o que fazer após a detecção do primeiro erro léxico, até porque a função `main` é fornecida. Mas uma opção seria parar o programa ao encontrar o primeiro erro léxico (ou seja, ao encontrar `TOKEN_ERRO[']`.

**Comment by otaviojacobi** [comment]
Nessa mesma linha, seria necessario tratar um caractere que é descrito por mais de um caractere no código ? Como por exemplo ```\n``` ou ```\0``` são caracteres validos ?
