### ISSUE TITLE
Resposta para o exercício de subconjuntos.org

### ISSUE THREAD

**Issue by schnorr** [schnorr/comp#34]
Alguém pode verificar se a resposta abaixo para [este Exercício](https://github.com/schnorr/comp/blob/master/conteudo/aulas/lexica/subconjuntos.org#5-exerc%C3%ADcio-converter-afnd-para-afd--er-ababb) está correta? Trata-se da aplicação do algoritmo de subconjuntos para criar o AFD a partir [deste AFND](https://github.com/schnorr/comp/blob/master/conteudo/aulas/lexica/subconjuntos.org#5-exerc%C3%ADcio-converter-afnd-para-afd--er-ababb), da expressão regular `(a|b)*abb`.

```
Estados do AFND         Estado AFD      a   b
{0, 1, 2, 4, 7}         A (inicial)     B   C
{1, 2, 3, 4, 6, 7, 8}   B               B   D
{1, 2, 4, 5, 6, 7}      C               B   C
{1, 2, 4, 5, 6, 7, 9}   D               B   E
{1, 2, 4, 5, 6, 7, 10}  E (final)       B   C 
```

**Comment by AvatarHurden** [comment]
@schnorr, parece estar tudo correto.
