### ISSUE TITLE
Tratamento de erro em identificador começando com número.

### ISSUE THREAD

**Issue by otaviojacobi** [schnorr/comp#39]
No caso a especificação cita que: 

```Os identificadores da linguagem são formados por um caractere alfabético seguido de zero ou mais caracteres alfanuméricos, onde considera-se caractere alfabético como letras maiúsculas ou minúsculas ou o caractere sublinhado e onde dígitos são 0, 1, 2, …, 9. ```

Mas no caso de fazermos algo como ```int 3test;``` isso deixa ambiguo se deve:
1 -> Lançar um token de erro léxico.
2 -> classificar como: TK_PR_INT[int] TK_LIT_INT[3] TK_IDENTIFICADOR[test] e futuramente lançar um erro sintático.

Qual das duas abordagens devemos seguir ?

**Comment by schnorr** [comment]
A abordagem 2 deve ser seguida, retornando:
```
TK_PR_INT[int]
TK_LIT_INT[3]
TK_IDENTIFICADOR[test]
```
Depois resolveremos isso com o analisador sintático.
