### ISSUE TITLE
Dúvida sobre criação de repositório para o projeto

### ISSUE THREAD

**Issue by FranciscoKnebel** [schnorr/comp#4]
Seguindo a definição do projeto de compilador, é instruído para criar um fork do repositório [schnorr/pc](https://github.com/schnorr/pc), mas pelo que entendi do discutido em aula, os repositórios devem ser privados, onde surge um problema, já que o Github não deixa alterar o modo de visibilidade de forks (no caso, [schnorr/pc](https://github.com/schnorr/pc) é público, logo não pode deixar de ser público).

# Solução 1

Uma solução que encontrei seria criar um repositório novo, não um fork, com todo o histórico do original, assim podendo criar um repositório privado. Receber novas modificações do repositório base seria apenas questão de adicionar um remote e dar um pull.

StackOverflow sobre essa questão: https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private

Nesse link, exemplos de código para criação do novo repositório.

# Solução 2

Usar a ferramenta de importação de projeto do GitHub em [https://github.com/new/import](https://github.com/new/import). Alterações no original funcionam da mesma forma que a solução 1.

------
Segui com essa primeira solução, mas ambas devem funcionar.

**Comment by schnorr** [comment]
Olá Francisco, confirmo que os repositórios dos grupos devem ser privados. Acredito que a Solução 2 seja mais simples para aqueles que tem menor experiência com GIT. Alterei a especificação do projeto de compilador para refletir essas possibilidades.
