### ISSUE TITLE
Operadores especiais %>%  e %|%

### ISSUE THREAD

**Issue by rodrigohrech** [schnorr/comp#41]
Olá!

Eu tenho uma dúvida quanto reconhecimentos dos tokens para operadores especiais: `%>%` e `%|%`

Eu devo reconhecer os % ou ele seria um placeholder? como deveria ser um output de exemplo?

**Comment by schnorr** [comment]
A sequência de caracteres `%`, `>` e `%`, quando aparecer sem nenhum espaço entre os caracteres, deve ter como ação o retorno do token identificado por `TK_OC_FORWARD_PIPE`. Reciprocamente, a sequência `%`, `|` e `%` deve ser mapeada para o token `TK_OC_BASH_PIPE`. Esses pipes são inspirados das linguagens R e bash.

Ou seja, respondendo a tuas perguntas:

- [X] **Eu devo reconhecer os % ou ele seria um placeholder?** O `%` não é um _placeholder_.

- [X] **Como deveria ser um output de exemplo?** A função `main` fornecida já cuida disso, ela imprime na tela (exemplo com número de linha qualquer):
```
123 TK_OC_FORWARD_PIPE [%>%]
123 TK_OC_BASH_PIPE [%|%]
```
