### ISSUE TITLE
Criação do arquivo .tgz para entrega

### ISSUE THREAD

**Issue by D-to-the-K** [schnorr/comp#43]
Seguindo as instruções para gerar o arquivo compactado, incorre-se em erro de execução do programa tar.

Instruções:
> "Cada grupo deve compactar o conteúdo do seu diretório de trabalho executando o comando `tar cvzf etapaX.tgz` (onde X é o dígito identificador da etapa) **dentro do mesmo diretório**."

Resultado:
> `user@debian:~/Desktop/Compiladores$ tar cvzf etapa1.tgz`
> `tar: Cowardly refusing to create an empty archive`
> `Try 'tar --help' or 'tar --usage' for more information.`

Solução:
Executar o comando `tar cvzf etapaX.tgz *` no lugar do comando citado.

**Comment by auzaitavares** [comment]
Você pode passar no comando só os arquivos que quer zipar:
``tar cvzf etapa1.tgz main.c tokens.h scanner.l``
