### ISSUE TITLE
Ambiguidade em Variáveis Globais

### ISSUE THREAD

**Issue by AvatarHurden** [schnorr/comp#44]
Na declaração de variáveis globais, há uma ambiguidade em relação à ordem dos componentes.

No trecho

> As variáveis são declaradas pelo seu nome, seguido do seu tipo.

entende-se que o tipo da variável vem depois do seu nome. Porém, o trecho

>  [...] declaração de vetores, [...] colocada **à direita do nome**, ou seja, ao **final da declaração.**

dá a entender que o nome é a última coisa da declaração (desconsiderando a notação de vetores).

Qual das duas interpretações é a correta?

**Comment by schnorr** [comment]
Corrigido em 5164010. A primeira interpretação é correta.
