### ISSUE TITLE
Uso de tipos de usuários em comandos no bloco de comando de uma função

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#48]
Na especificação da etapa 2, não ficou muito claro o espaço que tipos de usuários (definidos utilizando a palavra reservada `class`) desempenham na linguagem:

1. Segundo a especificação de variáveis globais, uma variável pode ser vetorizada, e pode ser de um tipo de usuário (e.g. `new_var[5] new_type;`), porém, não há comando de atribuição que prevê esse caso, contendo na especificação apenas comando de atribuição para tipos de usuário não vetorizados.
> Para os identificadores cujo tipo é aquele declarado pelo usuário pode ter seus campos acessados diretamente através do operador $, assim:
> ```
> identificador$campo = expressão
> ```
Não deveria também estar previsto um comando de atribuição levando em conta que variáveis globais de tipos de usuário podem ser vetorizadas? Algo no estilo:
```
identificador[expressão]$campo = expressão
```

2. Em comandos shift, ignora-se vetores de forma geral, tanto para tipos primitivos quanto pra tipos de usuário:
> Comandos de Shift
> Sendo número um literal inteiro positivo, temos:
> ```
> identificador << numero
> identificador >> numero
> ```
Não deveria ser possível uma operação para vetores e para tipos de usuário do tipo:
```
identificador$campo << número
identificador[expressão] << número
identificador[expressão]$campo << número
```
E também não deveria ser possível utilizar qualquer expressão no comando shift?
```
identificador << expressão
```

3. Na definição de expressões aritméticas e lógicas, também não há nenhuma menção de que operandos possam ser de um tipo de usuário. As operações a seguir não são previstas pela especificação:
```
identificador$campo op expressão
identificador[expressão]$campo op expressão
```
Isso deveria ser possível?

4. Na especificação de tipos de usuários, fica definido que uma classe tem apenas campos de tipo primitivo. Uma classe é, portanto, apenas uma estrutura de dados. Faz sentido a especificação de encapsulamento dos campos de uma classe, uma vez que um campo privado nunca será acessado ou manipulado de forma alguma, e que um campo protegido também nunca será acessado ou manipulado, ainda mais com a ausência de hierarquia na especificação da linguagem? Da forma como a linguagem é especificada hoje, os modificadores de encapsulamento poderiam ser removidos, e não se perderia nada.

**Comment by schnorr** [comment]
Sobre a questão 1, veja a16d65ba4a9042e0bdb0ab6f0a09d32f29884f65. Sobre a questão 2, veja 039da838a7bd2a0652a68aac9da6be8e0068889c. Sobre a questão 3, veja 354a40bf19991a4348f7ff333115d33a4c124746. E, sobre a questão 4, de fato os modificadores de acesso tem pouco efeito, mas vamos mantê-los para possível modificação futura.

**Comment by D-to-the-K** [comment]
Nestes casos citados, devemos prever também arrays multidimensionais, como:
mat[x][y] = 2;
?

**Comment by schnorr** [comment]
Não existe nenhum indício na [Especificação da Etapa 2](https://github.com/schnorr/comp/blob/master/projeto/etapa2.org) que a linguagem deva suportar, neste momento, variáveis multidimensionais. Mas se o grupo decidir implementar, ele é encorajado para o fazer.
