### ISSUE TITLE
Especificação de expressões

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#49]
Na especificação da etapa 2 é definido que os operandos de expressões aritiméticas podem ser de três tipos: identificadores, literais e chamadas de função.

> As expressões podem ser de três tipos: aritméticas, lógicas, e com pipes. As expressões aritméticas podem ter como **operandos**: (a) identificadores, opcionalmente seguidos de expressão inteira entre colchetes, para acesso a vetores; (b) literais numéricos como inteiro e ponto-flutuante; (c) chamada de função. As expressões aritméticas podem ser formadas recursivamente com operadores aritméticos, assim como permitem o uso de parênteses para forçar uma associatividade diferente daquela tradicional, à esquerda.

Fica subentendido que esse três tipos podem apenas ser usados quando em conjunto de uma operação, como por exemplo no caso de um comando de atribuição `identificador = local_var + 12 - f();`.

Na especificação não fica claro se esses três tipos são eles mesmo uma expressão, podendo os utilizar sem a necessidade de uma operação aritmética, lógica ou com pipes.

```
identificador = local_var;
identificador = 13;
identificador = f();
```

Isso é válido na linguagem?

**Comment by schnorr** [comment]
Sim. Veja  e796437.

**Comment by D-to-the-K** [comment]
É sabido que `expressões` podem ser aritméticas, lógicas, e funções com ou sem _pipes_, e podem ser associadas e combinadas através de diversos operadores unários e binários.

Para esta etapa, devemos impedir que sejam feitas combinações impróprias com relação ao tipo das expressões, dado o operador usado? Em outras palavras, o comando abaixo seria válido, apesar de misturar expressões lógicas e aritméticas?
`x = (a && b + 5) * 2;`
