### ISSUE TITLE
Testes E1 atualizados?

### ISSUE THREAD

**Issue by FranciscoKnebel** [schnorr/comp#5]
Só uma dúvida, pois no teste 44 ele utiliza o caractere especial $, que não está na definição atual do projeto, e deve retornar como caractere válido.
Adicionar é questão de uma linha a mais no scanner, só quero ter certeza.

**Comment by schnorr** [comment]
Como conversamos em aula, o que vale é a especificação e não os testes automáticos. Os testes serão atualizados depois, mas podem ser atualizados antes pelos grupos caso estes desejam.
