### ISSUE TITLE
Ponto-e-vírgula nos comandos das listas do for

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#50]
Na especificação da etapa 2, é definido que no comando for, os comandos das listas de comand devem ser separadas por vírgula. Porém, cada comando na especificação define seu próprio término com ou sem ponto-e-vírgula. Qual é o formato adequado para o comando for? Ainda, o comando for exclui apenas os comandos input, output e case, podendo o comando for ter em sua construção comandos do tipo if-then-else, foreach, while-do, do-while, e até mesmo o próprio comando for.

1. Esse seria o uso mais comum do comando for, levando em conta o espírito de outras linguagens de programção tradicionais. De acordo com a especificação, os comandos devem terminar com ponto-e-vírgula:
```c
for (i = 0; : expressão : i = i + 1;) { ... }
```

2. Acredito que o objetivo de permitir uma lista de comandos no comando for seja para que contruções como essa sejam possíveis, que também são comuns em outras linguagens de programação. Com múltiplos comandos, começa a ficar estranho a presença do ponto-e-vírgula, porém, ainda está correto de acordo com a especificação.
```c
for (i = 0;, j = 0; : expressão : i = i + 1;, j = j + 1;) { ... }
```

3. A especificação permite uma flexibilidade muito grande para os comandos que podem estar presentes no comando for. Note que não há ponto-e-vírgula ao fim do comando condicional, pois o mesmo não deve terminar com ponto-e-vírgula.
```c
for (if (expressão) then { i = 0; } else { i = 10; } : expressão : if (expressão) { i = i + 1; }) { ... }
```

4. Coisas bizarras são permitidas com a especificação atual.
``` c
for (for (for ( i = 0;, k = 2;, do {...} while (expressão); : expressão : i = i + 1;) {...}, if (expressão) then { j = j + 2; } : expressão : i = i - 1) {...} : expressão : i = i + j;, j = i - j;) { ... }
```
breakdown:
```c
for // primeiro for
  ( for // início da primeira lista de comandos do primeiro for, segundo for
    ( for // início da primeira lista de comandos do segundo for, terceiro for
      ( i = 0;, k = 2;, do {...} while (expressão); // primeira lista de comandos do terceiro for
      : expressão // expressão do terceiro for
      : i = i + 1;) {...} /* segunda lista de comandos do terceiro for */, if (expressão) then { j = j + 2; } // fim da primeira lista de comandos do segundo for
    : expressão // expressão do segundo for
    : i = i - 1) {...} // fim da primeira lista de comandos do primeiro for, segunda lista de comandos do segundo for
  : expressão // expressão do primeiro for
  : i = i + j;, j = i - j;) { ... } // segunda lista de comandos do primeiro for
```

Isso é o esperado da linguagem?

**Comment by schnorr** [comment]
De acordo com a [especificação da Etapa 2](https://github.com/schnorr/comp/blob/master/projeto/etapa2.org), os comandos simples são terminados por ponto-e-vírgula, de acordo com a passagem.

> Um bloco de comandos é definido entre chaves, e consiste em uma
> sequência, possivelmente vazia, de comandos simples cada um *terminado*
> por ponto-e-vírgula.

Veja o esclarecimento sobre isso em  #51 e #54. Isso diz respeito ao comentário fornecido no item 3, pois tratando-se de comandos simples (mesmo dentro do `for`), comandos simples devem ser terminados por ponto-e-vírgula.

Obrigado pelo breakdown no item 4. De fato, a especificação da etapa 2 permite isso (assumindo que todos os comandos simples são terminados por ponto-e-vírgula conforme já discutido).

**Comment by AvatarHurden** [comment]
@schnorr, a passagem que você citou se refere a comandos simples *dentro* de um bloco de comandos. Porém, na definição do comando `for`, é dito que

> Os dois marcadores lista do comando for são listas de comandos separados por vírgula.

Ou seja, os comandos não estão dentro de um bloco de comandos. A especificação não deixa clara se comandos **fora** de blocos de comandos devem ou não ser terminados por ponto-e-vírgula.

**Comment by schnorr** [comment]
Veja 9ee73adca2ba5a064148936fc8cc9028fbcb55cd, uma modificação que tenta ser mais explícita nesse sentido.

**Comment by D-to-the-K** [comment]
Professor, a especificação impede o uso do comando `output` na lista do `for`, justificando com o fato de ele possuir vírgula. Tem algum motivo para impedir isso, ao mesmo tempo em que se permite o uso do próprio comando `for`, que também poderá ter vírgula (nas listas de comandos, ou dentro do bloco de controle, caso este use o comando `output`)? Vou ilustrar.

Este é um comando válido segundo a especificação:
```
for (
       int i = 0;                       // lista 1 do for
     , int lim = 5;                     // lista 1 do for
     : i < lim                          // expressão do for
     : i = i + 1;                       // lista 2 do for
    )          
{                                       // abre o bloco do for
    output i + 1;                       // comando do for
};                                      // fecha o bloco do for
```

Este é um comando válido segundo a primeira resposta nesta issue:
```
for
    (
       int i = 0;                       // lista 1 do for 1
     , int lim = 0;                     // lista 1 do for 1
     , for                              // lista 1 do for 1
           (
            int j = 0;                  // lista 1 do for 2
            , int lim2 = 5;             // lista 1 do for 2
            : j < lim2                  // expressão do for 2
            : j = j + 1;                // lista 2 do for 2
           )
       {                                // abre o bloco do for 2
            lim = j;                    // comando do for 2
       };                               // fecha o bloco do for 2
     : i < lim                          // expressão do for 1
     : i = i + 1;                       // lista 2 do for 1
    )
{                                       // abre o bloco do for 1
    output lim, i;                      // comando output do for 1
};                                      // fecha o bloco do for 1
```

E entendo que não sou impedido de usar um comando output dentro do bloco de comandos do segundo `for`, de modo que este também seria um comando válido:
```
for
    (
       int i = 0;                       // lista 1 do for 1
     , int lim = 0;                     // lista 1 do for 1
     , for                              // lista 1 do for 1
           (
            int j = 0;                  // lista 1 do for 2
            , int lim2 = 5;             // lista 1 do for 2
            : j < lim2                  // expressão do for 2
            : lim2 = j + 1;             // lista 2 do for 2
           )
       {                                // abre o bloco do for 2
            lim = j;                    // comando do for 2
            output i, lim, j, lim2;     // comando output do for 2
       };                               // fecha o bloco do for 2
     : i < lim                          // expressão do for 1
     : i = i + 1;                       // lista 2 do for 1
    )
{                                       // abre o bloco do for 1
    output lim, i;                      // comando output do for 1
};                                      // fecha o bloco do for 1
```

Ao meu ver, se conseguimos aninhar o `for` na lista de outro `for` (graças ao `;` que separa os comandos), também conseguimos colocar lá um comando `output`.

De outro modo, se o comando `output` deve ser impedido "porque sim", deve ele também ser impedido de aparecer dentro do bloco de comandos do segundo `for`?

**Comment by schnorr** [comment]
@D-to-the-K, veja regramento explícito sobre ponto-e-vírgulas dentro das listas de comandos do comando `for`, em 9ee73adca2ba5a064148936fc8cc9028fbcb55cd, onde se regra que tais ponto-e-vírgula não devem aparecer. Sendo assim, não permitimos qualquer comando que contenha vírgulas dentro das listas de comandos do comando `for`. Caso o comando na lista seja um bloco, deve-se seguir as regras tradicionais de bloco de comandos. É uma forma então de permitir os comandos `output` e `for` (e outros que tenha vírgulas) dentro das listas de um comando `for`.
