### ISSUE TITLE
Comandos como pipe como expressão

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#52]
Na especificação da etapa 2, fica definido que um comando pipe é um tipo de expressão, entretanto, não fica claro se um comando pipe pode ser usado como operador em outras expressões, aritméticas ou lógicas.

```
identificador = f() %>% g(.) + 2;
identificador = f() %>% g(.) || h(z);
```

Isso é válido na linguagem?

**Comment by schnorr** [comment]
Na [especificação da etapa 2](https://github.com/schnorr/comp/blob/master/projeto/etapa2.org), as expressões com pipes podem aparecer em lugares onde aparecem expressões aritméticas e lógicas:

> As expressões com pipes podem ser vistas como os comandos com pipes, detalhado na seção anterior.

Isso implica que sim, os dois exemplos acima são válidos.
