### ISSUE TITLE
Input com vírgula

### ISSUE THREAD

**Issue by AvatarHurden** [schnorr/comp#55]
Na definição dos comandos de fluxo de controle, é dito

> ... não podem aparecer comandos simples que contenham vírgulas, como o `output` e o `input`...

indicando que os dois comandos de entrada e saída possui vírgulas em suas definições.

Porém, na definição de `input`, é dito

> Identificado pela palavra reservada `input`, seguida de uma expressão.

Fica ambíguo se o `input` realmente possui vírgulas ou não e, caso não possua, se ele pode ser usado na lista de comandos do `for`.

**Comment by schnorr** [comment]
Como o `input` pode ter apenas uma expressão (sempre sem vírgulas, ele pode ser aceito dentro da lista de comandos do comando `for`. Veja 405011936b84fd417aef8d0ac899814ffa6369ae.
