### ISSUE TITLE
Mescla de expressões de diferentes tipos

### ISSUE THREAD

**Issue by camargodev** [schnorr/comp#58]
O enunciado diz:

> As expressões aritméticas podem ter como operandos: (a) identificadores [...]; (b) literais numéricos como inteiro e ponto-flutuante; (c) chamada de função.

Porém também diz:

>  Nesta etapa do trabalho não há distinção alguma entre expressões aritméticas, inteiras, de caracteres ou lógicas. A descrição sintática deve aceitar qualquer operadores e subexpressão de um desses tipos como válidos, deixando para a análise semântica das próximas etapas do projeto a tarefa de verificar a validade dos operandos e operadores.

Pela primeira parte, algo como `1 + true` seria inválido, mas pela segunda seria válido, uma vez que cabe a análise semântica recusar isso.

O que é o correto?

**Comment by schnorr** [comment]
Está correto a parte que diz que
> [..] não há distinção alguma entre expressões aritméticas, inteiras, de caracteres ou lógicas.
