### ISSUE TITLE
Virgulas e comandos dentro do for

### ISSUE THREAD

**Issue by otaviojacobi** [schnorr/comp#59]
Segundo a especificação
```
Estas listas não podem ser vazias. Nas duas listas dentro do for, não podem aparecer comandos simples que contenham vírgulas ou o comando case. 
```
Isso inclui chamada de funções ? pois elas podem OU não conter virgulas dentro dos (), devemos tratar isso ?

**Comment by D-to-the-K** [comment]
Professor, não entendi sua resposta. Algum dos comando abaixo é inválido por causa da chamada de função?
`for ( f() : true : g() ) { };
for ( f(x, y) : true : g(z) ) { };`

E preciso aproveitar para pedir que cessem essas alterações de última hora na especificação. Sorte a nossa de não termos enviado ainda, e termos tempo de mexer no que mais aparecer.
