### ISSUE TITLE
Versão do CMake para compilação

### ISSUE THREAD

**Issue by lahagemann** [schnorr/comp#6]
Como perguntado em aula, não está relatado se é necessário uma versão específica do cmake para buildar o projeto. Obtivemos erros com cmake 2.8 e 3.2. 

Segundo o professor, a versão que pode ser utilizada sem problemas é a 3.10 e/ou realizar um revert do commit que adiciona REPORT_FILE (ou VERBOSE, não tenho certeza) na regra BISON_TARGET do CMakeLists.txt.

**Comment by schnorr** [comment]
Obrigado @lahagemann pelo esclarecimento. Ou se reverte o commit https://github.com/schnorr/pc/commit/692ccec1828598fd19968c6d08aa418b88265677, ou se atualiza o cmake para uma versão recente.
