### ISSUE TITLE
Atribuição e expressões com operando campo de classe

### ISSUE THREAD

**Issue by CapsuleMaglev** [schnorr/comp#60]
Atribuições do tipo:

`identificador[expressão]$campo = identificador[expressão]$campo`
`identificador$campo = identificador[expressão]$campo`
`...`
(e suas derivações)

Assim como:
`identificador[expressão]$campo op identificador[expressão]$campo`
`identificador$campo op identificador[expressão]$campo`
`...`
(e suas derivações)

São válidas?

**Comment by schnorr** [comment]
@CapsuleMaglev. São válidas, veja a questão #48, em especial a questão 3.
