### ISSUE TITLE
Expressões podem ser strings/chares?

### ISSUE THREAD

**Issue by CaioFRodrigues** [schnorr/comp#61]
Na especificação não consta nada que diga que expressões possam ser strings ou chares, no entanto isso significaria que comandos como _return "False"_, ou _x = 'c'_ só não funcionam e os chares na linguagem se tornam meio inúteis. Devemos colocar chares e strings nas expressões ou deixar de fora desses comandos e atribuições?

**Comment by schnorr** [comment]
Olá @CaioFRodrigues, de fato strings/chares foram esquecidos na [especificação da etapa 2](https://github.com/schnorr/comp/blob/master/projeto/etapa2.org#expr-aritm%C3%A9ticas-l%C3%B3gicas-e-com-pipes), mas eu entendo que os teus exemplos como `return "false"` e `x = 'c'` são naturais e possíveis na linguagem.
