### ISSUE TITLE
Relação bloco de comando - comando simples

### ISSUE THREAD

**Issue by marcelluscf** [schnorr/comp#62]
Boa noite, professor.

A seguinte frase

"Um bloco de comandos é considerado como um comando único simples, recursivamente, **e pode ser utilizado em qualquer construção que aceite um comando simples.**"

me deixou confuso sobre se o programa deveria aceitar algo como

int main() 
{
{
{
}
}
}

Ele deve aceitar ou rejeitar?

**Comment by schnorr** [comment]
Na [Especificação da Etapa 2](https://github.com/schnorr/comp/blob/master/projeto/etapa2.org), temos que:

> Um bloco de comandos é definido entre chaves, e consiste em uma sequência, possivelmente vazia, de comandos simples cada um terminado por ponto-e-vírgula. Um bloco de comandos é considerado como um comando único simples, recursivamente, e pode ser utilizado em qualquer construção que aceite um comando simples.

Portanto a tua entrada esta errada pois no bloco da função o seu único comando simples não está terminado por ponto-e-vírgula. O mesmo se repete na bloco mais aninhado. Estando errada, ele deve rejeitar (não pela razão da tua dúvida, mas sim pela falta da marcação correta do ponto-e-vírgula). Mas indo para a tua pergunta, note que a palavra `recursivamente` é usada na especificação, portanto um bloco de comandos pode conter outro bloco de comandos.
