### ISSUE TITLE
Teste automatizado da etapa 2 não bate com a especificação

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#64]
No teste **asl117**, é testada a possibilidade de um campo de um tipo de usuário ser definido como vetor:
```
//O tipo de um campo que faz parte uma declaração de novo tipo pode 
//ser de qualquer tipo, salvo um tipo de usuário, ou seja, um tipo
//declarado com class.
//o tipo do campo pode ser vetor
int func1(char param1) {
    MinhaClasse a;
    a$nome[0] = 3.5;
}
```

A primeira frase desse teste é tirada diretamente da especificação:
> O tipo de um campo que faz parte de uma declaração de novo tipo pode ser de qualquer tipo, salvo um tipo de usuário, ou seja, um tipo declarado com class.

Porém, a frase "o tipo do campo pode ser vetor" é um fato novo, nunca mencionado na especificação de tipos de usuário.

Ao longo da especificação, sempre somos avisados se algum elemento pode ou não ser vetorizados:

> A linguagem inclui também a declaração de **vetores**, feita pela definição de seu tamanho inteiro positivo entre colchetes, colocada à direita do nome.

> O cabeçalho consiste no tipo do valor de retorno, que não pode ser **vetor**, seguido pelo nome da função e terminado por uma lista.

> Cada parâmetro é definido pelo seu tipo e nome, e não pode ser do tipo **vetor**.

> As declarações locais, ao contrário das globais, não permitem **vetores** e podem permitir o uso da palavra reservada const antes do tipo (após a palavra reservada static caso esta aparecer).

> (a) identificadores, opcionalmente seguidos de expressão inteira entre colchetes, para acesso a **vetores**;

> As expressões podem consistir também somente por um dos elementos acima (a, b, c), uma sequência com pipes, e um tipo de usuário (**vetorizado** ou não)

Por conta da omissão dessa característica na especificação, se dá o entendimento claro que campos em tipos de usuário não podem ser vetorizados, e que esse teste pode ter sido usado por engano, uma vez que foi testado apenas o uso, e não a definição de um campo vetorizado em um tipo de usuário.

Faço também a observação que todos os grupos que apresentaram a etapa 2 falharam nesse específico teste, e acredito que a turma fez a interpretação correta da especificação para esse caso.

Peço, por gentileza, que reconsidere a utilização desse teste na avaliação da etapa 2.

**Comment by schnorr** [comment]
O teste `asl117` será removido da avaliação da E2.
