### ISSUE TITLE
Modificação do arquivo principal

### ISSUE THREAD

**Issue by lanahra** [schnorr/comp#68]
Como eu comentei na issue #67, seria vantajoso poder modificar o arquivo principal para pequenos ajustes, como inserir a chamada para a função yylex_destroy() para liberar a memória alocada pelo flex e bison, assim como modificar os includes para podermos organizar os arquivos de forma mais decente (por exemplo, arquivos header numa pasta include, arquivos source numa pasta src).

Para usar a função yylex_destroy() seria necessário incluir o header lex.yy.h. E para poder organizar a estrutura do projeto seguindo boas práticas de programação seria necessário alterar o caminho dos includes. Essa restrição ao arquivo principal adiciona uma barreira a mais para o desenvolvimento do trabalho que já é bastante complexo.

Já que existe uma forma objetiva de correção da etapa 3, que é independete de código específico, e até mesmo inclui a checagem por vazamento de memória, deveria ser permitido a livre edição do arquivo principal, para nós mesmos decidirmos a melhor maneira de organizar o código.

**Comment by schnorr** [comment]
@lanahra, obrigado pelas sugestões. Os argumentos são consistentes a favor de uma flexibilização a respeito da função principal do programa. Sendo assim, concordo que a partir da E3 é permitida a alteração da função `main` obedecendo as seguintes condições:
1. O arquivo `makefile` deve implementar a opção `make clean`
2. O comando `make clean` deve remover todos os árquivos `.o` e binário compilados (usando o comando `rm`)
3. O comando `make` deve executar a integralidade dos comandos necessários para reconstruir o binário a partir dos arquivos `scanner.f`, `parser.y` e demais arquivos `.c`.
