### ISSUE TITLE
Operadores compostos

### ISSUE THREAD

**Issue by DenysonJ** [schnorr/comp#7]
Na parte de operadores compostos, devemos retornar tokens. Entretanto existem dois operadores compostos  "%>%" e "%|%" que não possuem um token no arquivo parser.y

O que devemos fazer?

**Comment by schnorr** [comment]
Basta declarar os tokens correspondentes no arquivo `parser.y`, adotando nomes que são significativos para o grupo.

**Comment by FranciscoKnebel** [comment]
Mas precisa alterar o switch do arquivo main.c pra reconhecer também, da mesma forma que o caractere especial '.', onde é impresso o token.
