### ISSUE TITLE
Pergunta sobre o comando return

### ISSUE THREAD

**Issue by AvatarHurden** [schnorr/comp#75]
A linguagem não tem funções `void`, visto que existem apenas os tipos `int`, `float`, `bool`, `char`, `string` e tipos de usuário (que precisam ter ao menos um campo), e toda função precisa ter um tipo.

É dito que precisamos verificar que o tipo da expressão do comando `return` seja adequada ao tipo de retorno da função a que ele pertence.

Deveríamos analisar a existência de um comando return em todas as funções, ou isso fica opcional na linguagem? Se precisarmos verificar que existe um return, isso deveria ser feito em todos os branches da função (garantindo que qualquer caminho retorna) ou apenas uma verificação simples?

**Comment by schnorr** [comment]
Veja o comentário do item 4 na issue #70. Ou seja, não há necessidade de fazer a verificação que tu descreveste. Mas caso fizerem, forneça no campo "comentários" que isso foi implementado.
