### ISSUE TITLE
Dúvida sobre tipos de usuário

### ISSUE THREAD

**Issue by D-to-the-K** [schnorr/comp#79]
Na especificação da etapa 4 é dito que

> Variáveis que são de tipo de usuário devem obedecer as regras impostas na declaração do respectivo tipo (ERR_USER).

Minha dúvida é se existe a obrigatoriedade de um tipo de usuário ser acessado pelo operador `$`.

Para ilustrar essa dúvida, pergunto se o código abaixo deve ser aceito pela verificação de tipos:

```
class C [ int campo ];

C main() {
    C tmp;
    return tmp;
}
```

**Comment by schnorr** [comment]
O código deve sim ser aceito pela verificação de tipos.
