### ISSUE TITLE
[PC - Etapa 1] Ponto flutuante com notação científica

### ISSUE THREAD

**Issue by leodorna** [schnorr/comp#8]
No enunciado diz: 
A notação científica é possível para números ponto flutuantes utilizando um **E** ou **e** seguindo de um número positivo ou negativo inteiro.
E a representação de um inteiro tem uma precedência opcional de um caractere '+' ou '-'.

Ficamos na dúvida se o inteiro à direita do [Ee] também tem uma precedência opcional de sinal ( "1.4E10" seria válido, por exemplo ) ou as notações válidas são ( 1.4E+10 e 1.4E-10 )

**Comment by schnorr** [comment]
O sinal positivo ou negativo de um número inteiro depois de um E ou e, na notação científica, é opcional.
