### ISSUE TITLE
Dúvidas sobre a saída de memória esperada

### ISSUE THREAD

**Issue by D-to-the-K** [schnorr/comp#80]
Boa tarde, professor.

Temos dúvidas sobre a saída esperada para o seguinte código, usando a opção `-m` do `ilocsim`:

```
int main() {
  int j <= 1;
  return 0;
}
```

Nosso compilador está atualmente produzindo a seguinte memória:
`00001020 1`

Nossas dúvidas são:
1) Este endereço está correto? Ou deveria ser `1024` no lugar do `1020`?
2) Há algo que devemos fazer com o valor do `return` da função `main`?

Apenas por curiosidade, o equivalente deste código em C é:
```
int main() {
    int i = 42;
    return 0;
}
```

Que, compilado pelo `GCC` e dumpado com o `objdump`, produz a seguinte saída:

```
00000000 <main>:
int main() {
   0:	55                   	push   ebp
   1:	89 e5                	mov    ebp,esp
   3:	83 ec 10             	sub    esp,0x10
   6:	e8 fc ff ff ff       	call   7 <main+0x7>
   b:	05 01 00 00 00       	add    eax,0x1
int i = 42;
  10:	c7 45 fc 2a 00 00 00 	mov    DWORD PTR [ebp-0x4],0x2a
return 0;
  17:	b8 00 00 00 00       	mov    eax,0x0
}
  1c:	c9                   	leave  
  1d:	c3                   	ret    
```

Isto indica que o GCC também primeiro decrementa o `ebp` (equivalente do nosso `rfp`) para então fazer o `mov` (equivalente ao nosso `store`).

**Comment by lanahra** [comment]
Lembro do professor comentando na aula que os dois ponteiros cresciam para o mesmo lado, diferentemente da linguagem C.

Então o programa:

```
a int;
b int;

int main() {
    a = 1;
    b = 2;
    int c <= 3;
    int d <= 4;
}
```

Resultaria na seguinte memória:

```
00000000 1
00000004 2
00001024 3
00001028 4
```

Considerando que as configurações padrões não foram modificadas, ou seja, `rbss = 0` e `rfp = 1024`.

**Comment by schnorr** [comment]
Olá @D-to-the-K. Adotaremos a abordagem apresentada pelo @lanahra, onde a pilha cresce de endereços menores para endereços maiores.
