### ISSUE TITLE
Dúvida sobre valor inicial de uma variavel

### ISSUE THREAD

**Issue by otaviojacobi** [schnorr/comp#81]
Quando declaramos uma variavel, como no seguinte programa: 
```
a int;
int main() {
  int j <= 2 * a;
 
}
```
Podemos considerar qual o valor em ```a``` vai ser inicialmente zero ? Ou seria lixo ? Ou cada grupo implementa isso como preferir ?

**Comment by schnorr** [comment]
Olá @otaviojacobi, podemos adotar prática idêntica aquela da implementação do gcc da linguagem C. Nela, as variáveis globais são "zeradas", ou seja, recebem zeros no local de seu vínculo de estocagem.
