### ISSUE TITLE
[E6] Problema recursão (e como resolvê-lo)

### ISSUE THREAD

**Issue by PedroCardouzo** [schnorr/comp#82]
Atualmente, pode haver um problema com recursão

```
return x + y; vira algo tipo 
load R1 x
load R2 y
add x y R3
return R3

Isso gera um problema ao fazer

return n*factorial(n-1) ->
1    load R1 n
2    load R2 n
3    sub  R2 1
4    call factorial R2 => R3 // suponha que o valor resultante da call para factorial é colocada em R3 e é passado o parametro R2 -- abstração
5    MULT R1, R3 // perceba que o valor de R1 foi carregado antes da função ser chamada

Problema:
vamos acompanhar a execução; suponha factorial(4):
1   load R1 n // R1 = 4
2   load R2 n // R2 = 4
3   sub  R2 1 // R2 = 3
4   call factorial R2 => R3 // R3 = factorial(3)
1   load R1 n // R1 = 3 // <<<<<<<<< aqui acontece um problema: R1 é sobreescrito e ao voltarmos da
// chamada anterior de factorial ele continua com o valor que foi carregado dentro da função interior, 
// pois carregamos o n para R1 antes de chamar a função
.
.
.
5   mult R1, R3 // -> R1 não vai ter mais o valor de n dessa função (4), mas sim o colocado pela ultima função que sobreescreveu o R1.
```

Isso acontece pois 
Carregamos o valor de R1
chamamos a função
Essa função carrega novamente o valor de n (mas agora, um novo n) em R1, pois ela executa o exato mesmo código (a chamada é basicamente um jump pro inicio da função)

Normalmente isso é ok pois ao chamar uma função salvamos os estados dos registradores e ao voltar dela só temos que restaurá-los, todavia, não podemos fazer isso em ILOC de forma simples, visto que temos potencialmente infinitos registradores.

Todavia a resolução é simples e nem envolve o compilador diretamente, mas sim o codigo sendo compilado:

em vez de fazer:
```
int factorial(int n){
	return n*factorial(n-1);
}
```

deve-se usar:

```
int factorial(int n){
	int aux;
	aux = factorial(n-1);
	return n*aux;
}
```

```
Desse modo, carregamos o valor de n depois da chamada recursiva:
factorial(4)
load 0 R4 // aux inicializado
(parametros, aux e tal; também usei os mesmos registradores para as mesmas utilidades para dar mais clareza)
load R2 n // R2 = 4
sub  R2 1 // R2 = 3
call factorial R2 => R3
move R3 => R4 // aux = R3
load R1 n // R1 = 4
MULT R1, R4 // nesse caso carregamos o R1 logo antes de fazer a multiplicação, mas depois de passar pela chamada de função
assim, R1 não se encontra "bufferizado" antes da chamada recursiva e não é sobreescrito pela função mais interna

```
**TL;DR -> faça testes de recursão**

assim:
```
	x = fib(n-1);
	y = fib(n-2);
	return x+y;
```
e não assim:
`	return fib(n-1)+fib(n-2);`

assim: 
```
	x = factorial(n-1);
	return x*n;
```
e não assim:
`	return n*factorial(n-1);`

em suma, **não tenha chamadas RECURSIVAS junto com outras operações**, sempre que for fazer uma chamada de função, a isole em uma variavel temporária (a princípio isso só deveria afetar a recursão já que o problema é que estamos escrevendo algo em cima de um registrador já usado)

**Comment by PedroCardouzo** [comment]
adicionalmente outras maneiras de resolver isso em teoria seriam sempre que possível fazer
return f(n-1)*n, assim não carregariamos o n para o registrados antes de chamar f(n-1). Tem praticamente o mesmo resultado mas só funciona com funções recursivas lineares (como não temos vetores, foi chamá-las de O(n), mas deve dá pra fazer algumas que fazem umas somas loucas que seriam O(n^2). Por exemplo, não funcionaria com fibonacci.

Para fibonacci poderia-se fazer tail recursion:
```
int fib(int n){
    return _fib(n, 0, 1);
}

int _fib(int n, int a, int b){ 
    if (n == 0) then{
        return a; 
    };
    if (n == 1) then{
        return b; 
    };
    return _fib(n - 1, b, a + b); 
} 
```
**Todavia esses métodos nao foram testados ainda (to no trabalho)**

**Comment by schnorr** [comment]
Uma opção é salvar na pilha todos os temporários em uso no bloco até a chamada de função; e depois, após o retorno, restaurá-los.

**Comment by PedroCardouzo** [comment]
Também pensei nessa possibilidade, mas a principio foi dito que não usaríamos o machine state.
Então em suma tem que fazer o handling dos registradores também?
Fiquei com uma dúvida também se é desse modo que é implementado em casos reais?

**Comment by D-to-the-K** [comment]
Professor, reiterando a pergunta do Pedro, é necessário que façamos o salvamento e restauração de todos os temporários usando a pilha?

**Comment by schnorr** [comment]
Olá @D-to-the-K e @PedroCardouzo, obrigado por relançar esta questa. Não é necessário. Basta prever o espaço ocupado para o "estado da máquina", imaginando que aquele espaço espaço seria reservado para registradores físicos da arquitetura.

**Comment by vitorvanacor** [comment]
Isso significa que nos testes não haverá recursão (ou, se houverem, serão realizados como o Pedro descreveu)?

**Comment by schnorr** [comment]
Certamente teremos recursão nos testes. Serão realizados de acordo com a especificação.

**Comment by D-to-the-K** [comment]
Professor, se não salvarmos os temporários, a recursão não vai funcionar em todos os casos. A especificação prevê os dois jeitos que o @PedroCardouzo indicou. Vamos perder nota nos testes se o primeiro jeito não funcionar?

**Comment by vitorvanacor** [comment]
O ponto é que para uma recursão do tipo `return n * factorial(n-1)` funcionar é **necessário** salvar os registradores temporários (o "estado" da execução antes da chamada recursiva).
Em uma das respostas, tu afirmou que não seria necessário o salvamento e restauração dos temporários, bastando prever o espaço ocupado.
Das duas, uma: ou salvamos os temporários e toda recursão funciona; ou não salvamos e nem toda recursão funciona. Qual das duas? Se a especificação esclarece essa dúvida em alguma parte, não encontrei. Se alguém (professor ou algum aluno que tiver encontrado) puder me apontar, aceitarei.

**Comment by D-to-the-K** [comment]
Meh, agora já fizemos também. Não é muito complicado. Recomendo que todos façam, por via das dúvidas.

**Comment by schnorr** [comment]
Pessoal (@vitorvanacor @D-to-the-K @PedroCardouzo), lamento todo o imbróglio.

De maneira definitiva: **a recursão deve funcionar**. Se salvar valores de registradores for necessário para que a recursão funcione, então, sim, deve-se salvar os registradores.
