### ISSUE TITLE
Inserção de char e string na tabela de símbolos

### ISSUE THREAD

**Issue by FranciscoKnebel** [schnorr/comp#9]
Encontramos um problema ao inserir char e strings na tabela de símbolos, seguindo o definido no final do documento `projeto/etapa1.org`:
```
Os literais do tipo char e string devem ser inseridos na tabela de símbolos sem as aspas que os identificam no código fonte.
```
Testando o arquivo de avaliacao_02, encontramos os literais "<" e '<'. Se removermos as aspas **ANTES** de inserir na tabela, "<" e '<' serão considerados como a mesma chave na tabela, mas são dois símbolos diferentes, gerando um erro.

Inserindo literais do tipo string e char na tabela com as aspas e removendo ao utilizar o valor das chaves (na função de print, ao iterar sobre a tabela) resolveu o problema.

Devemos manter dessa forma, que corrigiu o problema, ou reverter? Creio que ambos literais devem ser tratados como elementos diferentes. Há formas mais eficientes para armazenar a diferença entre ambos tipos de literais, mas essa é a forma mais clara de explicar o problema.

**Comment by schnorr** [comment]
Uma solução é seguir o enunciado, removendo as aspas duplas/simples, e sobrescrever a entrada na tabela de símbolos (já que "<" e '<' são a mesma coisa).

**Comment by FranciscoKnebel** [comment]
Era o feito inicialmente, mas o arquivo de teste possuía dois símbolos < na tabela, um para a string e outro para o char.

Será considerado como a mesma coisa então, na tabela de símbolos.
